### ISSUE TITLE
mod_prebw not starting bash script in background

### ISSUE THREAD

**Issue by annoyinguser** [silv3rr/foo-tools#5]
Doing pre tests i always have to wait for slv-prebw.sh to finish. Bash script not spawned in background.
In chrooted glftpd there is no
#!/usr/bin/env bash 
It has to be
#!/bin/env bash

**Comment by silv3rr** [comment]
It's run like you would from shell: `slv-prebw.sh &`
https://github.com/silv3rr/foo-tools/blob/88d45f556d39d5aef3c27d5efe5ef803df8096da/src/pre/modules/mod_prebw.c#L233

after that foo-pre *should* continue right away and write PRE to gllog, log to foo-pre.log etc.

Now if there's anything written to stderr while running slv-prebw.sh, that would cause what you're saying. But slv-prebw should only log to gllog, so not sure whats up with that.

Anyways, it's fixed by a small change:
`	sprintf(buf, "nohup %s '%s/%s' 2>/dev/null &", prebw_bin, s_path, tmp);`

You're right about the shebang. The README.mod_prebw does mention req bins need to be in gldir.

**Comment by annoyinguser** [comment]
Okay i must admit i have modified slv-prebw to show top spreaders which will be received from xferlog (i am not a super pro bash guy as you are)... shows something like:
prebw > top 3 spreaders > 1 > uname1 > 39f > 1812.0MB > avg. 62.4MB/s > 2 > uname2 > 11f > 507.9MB > avg. 63.4MB/s > 3 > uname3 > 9f > 429.1MB > avg. 42.9MB/s
Maybe that is the reason it is not in "background"
